### ISSUE TITLE
ImportError: cannot import name Splitwise

### ISSUE THREAD

**Issue by maxrugen** [namaggarwal/splitwise#19]
Hey guys,

while executing a file splitwise.py containing `import splitwise as Splitwise` with `python splitwise.py`, I ran into an issue I did not quite understand. My terminal outputs the following:

```bash
Traceback (most recent call last):
  File "splitwise.py", line 1, in <module>
    from splitwise import Splitwise
  File "/Users/maxrugen/splitwise/splitwise.py", line 1, in <module>
    from splitwise import Splitwise
ImportError: cannot import name 'Splitwise'
```

Any ideas what might cause this? I looked the ImportError up on StackOverflow [here](https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x) but didn't quite get how that issue might be reflected in my case.

**Comment by maxrugen** [comment]
I'm blind. Didn't see the `requirements.txt` file. Excuse me.
